# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: yes
      nameservers:
        addresses: [10.3.0.2, 8.8.8.8]
    enp0s8:
      dhcp4: no
      addresses: [192.168.56.15/24]
      gateway4: 192.168.1.1
